# Python DA Assignment 1: Data Analysis using

NumPy and Pandas

In [9]:
#Numpy and array operations

In [10]:
import numpy as np

In [11]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [12]:
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [13]:
print(temperatures_w1.shape)

(7,)

In [14]:
print(temperatures_w1.dtype)

float64

In [15]:
print(temperatures_w1.size)

7

# Array Operations:

In [16]:
temperatures_w1_f = (temperatures_w1 * 9/5) + 32

In [17]:
print(temperatures_w1_f)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [18]:
print(temperatures_w1_f. min())

69.44

In [19]:
print(temperatures_w1_f. max())

78.98

In [20]:
print(temperatures_w1_f. mean())

74.37714285714286

In [21]:
print(f"Max: {temperatures_w1_f.max()}, Min: {temperatures_w1_f.min()}, Mean: {temperatures_w1_f.mean()}")

Max: 78.98, Min: 69.44, Mean: 74.37714285714286

# 4. Array Slicing and Indexing:

In [22]:
temperatures_w1[0:3]

array([22.5, 25.3, 20.8])

In [23]:
temperatures_w1[-2:]

array([24.8, 21.9])

In [24]:
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

*Create a 2D Array:*

In [25]:
temperatures = np.array ([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

In [26]:
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

# Inspect and Slice the 2D Array:

In [27]:
print(temperatures.shape)

(2, 7)

In [28]:
print(temperatures.dtype)

float64

In [30]:
print(temperatures.size)

14

In [29]:
print(temperatures[0] [-2 :])
print(temperatures[1]  [-2 :])

[24.8 21.9]
[22.8 20.1]

In [ ]:
print(temperatures[0])
print(temperatures[1])
print(temperatures[0, -2:])
print(temperatures[1, -2:])

# Pandas Series:

In [55]:
import pandas as pd

In [56]:
marks = pd.Series ([95, 92, 89, 85, 80])

In [57]:
print(marks)

0    95
1    92
2    89
3    85
4    80
dtype: int64

In [81]:
marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])

In [82]:
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

**2. Indexing and Slicing:**

In [60]:
marks.iloc[0]

np.int64(95)

In [80]:
marks.loc[['Rank1', 'Rank2', 'Rank3']]

Rank1    100
Rank2     92
Rank3     89
dtype: int64

In [62]:
marks.iloc[2]

np.int64(89)

In [63]:
marks[marks>90]

Rank1    95
Rank2    92
dtype: int64

**3. Manipulating Series:**

In [83]:
marks.loc["Rank1"] = 100

In [84]:
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [85]:
marks= marks.drop ('Rank5')

In [86]:
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [88]:
cgpa = marks / 10

In [89]:
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

# Pandas DataFrame:
1. Creating Pandas DataFrame:

In [111]:
import pandas as pd

In [112]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

In [113]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [100]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [101]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [102]:
transactions.shape

(10, 4)

In [103]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [105]:
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [116]:
transactions [['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [117]:
transactions.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [121]:
transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [122]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [123]:
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [125]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

# 3. Manipulating the DataFrame:

In [126]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

In [127]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [128]:
transactions['Discount'] = transactions['Amount'] * 0.1

In [129]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [131]:
transactions[transactions['TransactionID'] == 109]

   TransactionID ProductCategory Region  Amount  Discount
8            109       Furniture  South     350      35.0

In [132]:
transactions = transactions.drop(8)

In [133]:
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [134]:
transactions.drop('Discount', axis=1, inplace=True)

In [135]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400